### ISSUE TITLE
Error while installing Vector with brew

### ISSUE THREAD

**Issue by jeltok** [vectordotdev/homebrew-brew#17]
I am trying to install vector on my Intel based MacBook, Ventura 13.6

Running the following command
`
brew tap vectordotdev/brew && brew install vector
`

I see an error (below), and the installation fails

`
==> Fetching vectordotdev/brew/vector
==> Downloading https://packages.timber.io/vector/0.33.0/vector-0.33.0-x86_64-apple-darwin.tar.gz
###################################################################################################################################################################################### 100.0%
==> Installing vector from vectordotdev/brew
Error: inreplace failed
config/vector.yaml:
  expected replacement of /data_dir: ".*"/ with "data_dir: \"/usr/local/var/lib/vector/\""
`

**Comment by jszwedko** [comment]
Thanks for reporting this @jeltok ! It should be fixed now.

**Comment by jeltok** [comment]
Thank you for the quick turnaround!
